from typing import Dict, List, NamedTuple


stage_names = [
    "Viridian Forest",
    "Pewter City",
    "Mt Moon",
    "Cerulean City",
    "Vermilion City Seaside",
    "Vermilion City Streets",
    "Rock Mountain",
    "Lavender Town",
    "Cycling Road",
    "Safari Zone",
    "Fuchsia City",
    "Saffron City",
    "Seafoam Islands",
    "Cinnabar Island",
    "Indigo Plateau"
]


class PokePinballRegionData(NamedTuple):
    connecting_regions: List[str] = []

region_data_table: Dict[str, PokePinballRegionData] = {
    "Menu": PokePinballRegionData(["Red Table", "Blue Table"]),
    "Red Table": PokePinballRegionData([
        "Pallet Town",
        "Viridian Forest",
        "Pewter City",
        "Cerulean City",
        "Vermilion City Seaside",
        "Rock Mountain",
        "Lavender Town",
        "Cycling Road",
        "Safari Zone",
        "Seafoam Islands",
        "Cinnabar Island",
        "Indigo Plateau"]),
    "Blue Table": PokePinballRegionData([
        "Viridian City",
        "Viridian Forest",
        "Mt Moon",
        "Cerulean City",
        "Vermilion City Streets",
        "Rock Mountain",
        "Celadon City",
        "Safari Zone",
        "Fuchsia City",
        "Saffron City",
        "Cinnabar Island",
        "Indigo Plateau"]),

    "Pallet Town": PokePinballRegionData(["Bulbasaur","Charmander","Pidgey","Rattata","NidoranM","Poliwag","Tentacool"]),
    "Viridian City": PokePinballRegionData(["Bulbasaur","Squirtle","Spearow","NidoranF","NidoranM","Poliwag","Tentacool","Goldeen"]),
    "Viridian Forest": PokePinballRegionData(["Caterpie","Weedle","Pidgey","Rattata","Pikachu"]),
    "Pewter City": PokePinballRegionData(["Pidgey","Spearow","Ekans","Jigglypuff","Magikarp"]),
    "Mt Moon": PokePinballRegionData(["Rattata","Spearow","Ekans","Sandshrew","Clefairy","Zubat","Paras","Psyduck","Geodude","Krabby","Goldeen"]),
    "Cerulean City": PokePinballRegionData(["Caterpie","Weedle","NidoranM","Oddish","Psyduck","Mankey","Abra","Krabby","Goldeen","Jynx", "Meowth","Bellsprout"]),
    "Vermilion City Seaside": PokePinballRegionData(["Pidgey","Spearow","Ekans","Oddish","Mankey","Farfetchd","Shellder","Drowzee","Krabby"]),
    "Vermilion City Streets": PokePinballRegionData(["Pidgey","Spearow","Sandshrew","Meowth","Bellsprout","Farfetchd","Shellder","Drowzee","Krabby"]),
    "Rock Mountain": PokePinballRegionData(["Rattata","Spearow","Ekans","Zubat","Diglett","Machop","Geodude","Slowpoke","Onix","Voltorb","Mr Mime"]),
    "Lavender Town": PokePinballRegionData(["Ekans","Mankey","Growlithe","Magnemite","Gastly","Cubone","Electabuzz","Zapdos"]),
    "Celadon City": PokePinballRegionData(["Pidgey","Vulpix","Oddish","Meowth","Mankey","Growlithe","Bellsprout","Abra","Scyther","Pinsir","Eevee","Porygon","Dratini"]),
    "Cycling Road": PokePinballRegionData(["Rattata","Spearow","Tentacool","Doduo","Krabby","Lickitung","Goldeen","Magikarp","Snorlax"]),
    "Fuchsia City": PokePinballRegionData(["Venonat","Krabby","Exeggcute","Kangaskhan","Goldeen","Magikarp"]),
    "Safari Zone": PokePinballRegionData(["NidoranM","Paras","Doduo","Rhyhorn","Chansey","Scyther","Tauros","Dratini", "NidoranF","Pinsir"]),
    "Saffron City": PokePinballRegionData(["Pidgey","Ekans","Sandshrew","Vulpix","Oddish","Meowth","Mankey","Growlithe","Hitmonlee","Hitmonchan","Lapras"]),
    "Seafoam Islands": PokePinballRegionData(["Zubat","Psyduck","Tentacool","Slowpoke","Seel","Shellder","Krabby","Horsea","Goldeen","Staryu","Articuno"]),
    "Cinnabar Island": PokePinballRegionData(["Vulpix","Growlithe","Ponyta","Omanyte","Kabuto", "Koffing","Grimer","Tangela","Magmar","Aerodactyl"]),
    "Indigo Plateau": PokePinballRegionData(["Spearow","Ekans","Zubat","Sandshrew","Machop","Geodude","Onix","Ditto","Moltres","Mewtwo","Mew"]),

    "Bulbasaur": PokePinballRegionData(),
    "Charmander": PokePinballRegionData(),
    "Squirtle": PokePinballRegionData(),
    "Caterpie": PokePinballRegionData(),
    "Weedle": PokePinballRegionData(),
    "Pidgey": PokePinballRegionData(),
    "Rattata": PokePinballRegionData(),
    "Spearow": PokePinballRegionData(),
    "Ekans": PokePinballRegionData(),
    "Pikachu": PokePinballRegionData(),
    "Sandshrew": PokePinballRegionData(),
    "NidoranF": PokePinballRegionData(),
    "NidoranM": PokePinballRegionData(),
    "Clefairy": PokePinballRegionData(),
    "Vulpix": PokePinballRegionData(),
    "Jigglypuff": PokePinballRegionData(),
    "Zubat": PokePinballRegionData(),
    "Oddish": PokePinballRegionData(),
    "Paras": PokePinballRegionData(),
    "Venonat": PokePinballRegionData(),
    "Diglett": PokePinballRegionData(),
    "Meowth": PokePinballRegionData(),
    "Psyduck": PokePinballRegionData(),
    "Mankey": PokePinballRegionData(),
    "Growlithe": PokePinballRegionData(),
    "Poliwag": PokePinballRegionData(),
    "Abra": PokePinballRegionData(),
    "Machop": PokePinballRegionData(),
    "Bellsprout": PokePinballRegionData(),
    "Tentacool": PokePinballRegionData(),
    "Geodude": PokePinballRegionData(),
    "Ponyta": PokePinballRegionData(),
    "Slowpoke": PokePinballRegionData(),
    "Magnemite": PokePinballRegionData(),
    "Farfetchd": PokePinballRegionData(),
    "Doduo": PokePinballRegionData(),
    "Seel": PokePinballRegionData(),
    "Grimer": PokePinballRegionData(),
    "Shellder": PokePinballRegionData(),
    "Gastly": PokePinballRegionData(),
    "Onix": PokePinballRegionData(),
    "Drowzee": PokePinballRegionData(),
    "Krabby": PokePinballRegionData(),
    "Voltorb": PokePinballRegionData(),
    "Exeggcute": PokePinballRegionData(),
    "Cubone": PokePinballRegionData(),
    "Hitmonlee": PokePinballRegionData(),
    "Hitmonchan": PokePinballRegionData(),
    "Lickitung": PokePinballRegionData(),
    "Koffing": PokePinballRegionData(),
    "Rhyhorn": PokePinballRegionData(),
    "Chansey": PokePinballRegionData(),
    "Tangela": PokePinballRegionData(),
    "Kangaskhan": PokePinballRegionData(),
    "Horsea": PokePinballRegionData(),
    "Goldeen": PokePinballRegionData(),
    "Staryu": PokePinballRegionData(),
    "Mr Mime": PokePinballRegionData(),
    "Scyther": PokePinballRegionData(),
    "Jynx": PokePinballRegionData(),
    "Electabuzz": PokePinballRegionData(),
    "Magmar": PokePinballRegionData(),
    "Pinsir": PokePinballRegionData(),
    "Tauros": PokePinballRegionData(),
    "Magikarp": PokePinballRegionData(),
    "Lapras": PokePinballRegionData(),
    "Ditto": PokePinballRegionData(),
    "Eevee": PokePinballRegionData(),
    "Porygon": PokePinballRegionData(),
    "Omanyte": PokePinballRegionData(),
    "Kabuto": PokePinballRegionData(),
    "Aerodactyl": PokePinballRegionData(),
    "Snorlax": PokePinballRegionData(),
    "Articuno": PokePinballRegionData(),
    "Zapdos": PokePinballRegionData(),
    "Moltres": PokePinballRegionData(),
    "Dratini": PokePinballRegionData(),
    "Mewtwo": PokePinballRegionData(),
    "Mew": PokePinballRegionData(),
}

def get_exit(region, exit_name):
    for exit in region.exits:
        if exit.connected_region.name == exit_name:
            return exit