from .Locations import BomberTLocationData
from typing import Dict

loc_map_data_table: Dict[str, BomberTLocationData] = {
    # Map Locations
    #Magnet Base
    "Magnet Map C9": BomberTLocationData(
        region="MagBase",
        type="map",
        code=0x1C2B85,
        address=0x352B8,
        mask=0x20,
    ),
    "Magnet Map B9": BomberTLocationData(
        region="MagBase",
        type="map",
        code=0x1C2B84,
        address=0x352B8,
        mask=0x10,
    ),
    "Magnet Map B8": BomberTLocationData(
        region="MagBase",
        type="map",
        code=0x1C2B83,
        address=0x352B8,
        mask=0x8,
    ),
    "Magnet Map B7": BomberTLocationData(
        region="MagBase",
        type="map",
        code=0x1C2B81,
        address=0x352B8,
        mask=0x2,
    ),
    "Magnet Map C7": BomberTLocationData(
        region="MagBase",
        type="map",
        code=0x1C2B82,
        address=0x352B8,
        mask=0x4,
    ),
    "Magnet Map B6": BomberTLocationData(
        region="MagBase",
        type="map",
        code=0x1C2B77,
        address=0x352B7,
        mask=0x80,
    ),
    "Magnet Map C6": BomberTLocationData(
        region="MagBase",
        type="map",
        code=0x1C2B80,
        address=0x352B8,
        mask=0x1,
    ),
    "Magnet Map C5": BomberTLocationData(
        region="MagBase",
        type="map",
        code=0x1C2B75,
        address=0x352B7,
        mask=0x20,
    ),
    "Magnet Map A6": BomberTLocationData(
        region="MagBase",
        type="map",
        code=0x1C2B76,
        address=0x352B7,
        mask=0x40,
    ),
    "Magnet Map A5": BomberTLocationData(
        region="MagBase Elifan",
        type="map",
        code=0x1C2B73,
        address=0x352B7,
        mask=0x8,
    ),
    "Magnet Map B5": BomberTLocationData(
        region="MagBase Elifan",
        type="map",
        code=0x1C2B74,
        address=0x352B7,
        mask=0x10,
    ),
    "Magnet Map A4": BomberTLocationData(
        region="MagBase Elifan",
        type="map",
        code=0x1C2B70,
        address=0x352B7,
        mask=0x1,
    ),
    "Magnet Map B4": BomberTLocationData(
        region="MagBase Elifan",
        type="map",
        code=0x1C2B71,
        address=0x352B7,
        mask=0x2,
    ),
    "Magnet Map B3": BomberTLocationData(
        region="MagBase Elifan",
        type="map",
        code=0x1C2B66,
        address=0x352B6,
        mask=0x40,
    ),
    "Magnet Map A3": BomberTLocationData(
        region="MagBase Elifan",
        type="map",
        code=0x1C2B65,
        address=0x352B6,
        mask=0x20,
    ),
    "Magnet Map C3": BomberTLocationData(
        region="MagBase Elifan",
        type="map",
        code=0x1C2B67,
        address=0x352B6,
        mask=0x80,
    ),
    "Magnet Map C4": BomberTLocationData(
        region="MagBase Elifan",
        type="map",
        code=0x1C2B72,
        address=0x352B7,
        mask=0x4,
    ),
    "Magnet Map B2": BomberTLocationData(
        region="MagBase Elifan",
        type="map",
        code=0x1C2B64,
        address=0x352B6,
        mask=0x10,
    ),
    "Magnet Map A2": BomberTLocationData(
        region="MagBase Elifan",
        type="map",
        code=0x1C2B63,
        address=0x352B6,
        mask=0x8,
    ),
    "Magnet Map B1": BomberTLocationData(
        region="MagBase Elifan",
        type="map",
        code=0x1C2B62,
        address=0x352B6,
        mask=0x4,
    ),
    "Magnet Map B0": BomberTLocationData(
        region="MagBase Elifan",
        type="map",
        code=0x1C2B61,
        address=0x352B6,
        mask=0x2,
    ),
    "Magnet Map A0": BomberTLocationData(
        region="MagBase Elifan",
        type="map",
        code=0x1C2B69,
        address=0x352B6,
        mask=0x1,
    ),

    # Pretty Base
    "Pretty Map F8": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2BC0,
        address=0x352BC,
        mask=0x1,
    ),
    "Pretty Map E8": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2BB7,
        address=0x352BB,
        mask=0x80,
    ),
    "Pretty Map D8": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2BB6,
        address=0x352BB,
        mask=0x40,
    ),
    "Pretty Map D7": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2BB5,
        address=0x352BB,
        mask=0x20,
    ),
    "Pretty Map D6": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2BB4,
        address=0x352BB,
        mask=0x10,
    ),
    "Pretty Map D5": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2BB2,
        address=0x352BB,
        mask=0x4,
    ),
    "Pretty Map C5": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2BB1,
        address=0x352BB,
        mask=0x2,
    ),
    "Pretty Map D4": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2BA3,
        address=0x352BA,
        mask=0x8,
    ),
    "Pretty Map E4": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2BA4,
        address=0x352BA,
        mask=0x10,
    ),
    "Pretty Map F4": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2BA5,
        address=0x352BA,
        mask=0x20,
    ),
    "Pretty Map E3": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2B95,
        address=0x352B9,
        mask=0x20,
    ),
    "Pretty Map F3": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2B96,
        address=0x352B9,
        mask=0x40,
    ),
    "Pretty Map D3": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2B94,
        address=0x352B9,
        mask=0x10,
    ),
    "Pretty Map D2": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2B92,
        address=0x352B9,
        mask=0x4,
    ),
    "Pretty Map D1": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2B91,
        address=0x352B9,
        mask=0x2,
    ),
    "Pretty Map D0": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2B90,
        address=0x352B9,
        mask=0x1,
    ),
    "Pretty Map C0": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2B87,
        address=0x352B8,
        mask=0x80,
    ),
    "Pretty Map B0": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2B86,
        address=0x352B8,
        mask=0x40,
    ),
    "Pretty Map C4": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2BA2,
        address=0x352BA,
        mask=0x4,
    ),
    "Pretty Map B4": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2BA1,
        address=0x352BA,
        mask=0x2,
    ),
    "Pretty Map A4": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2BA0,
        address=0x352BA,
        mask=0x1,
    ),
    "Pretty Map A5": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2BA7,
        address=0x352BA,
        mask=0x80,
    ),
    "Pretty Map B5": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2BB0,
        address=0x352BB,
        mask=0x1,
    ),
    "Pretty Map A6": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2BB3,
        address=0x352BB,
        mask=0x8,
    ),
    "Pretty Map G4": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2BA6,
        address=0x352BA,
        mask=0x40,
    ),
    "Pretty Map G3": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2B97,
        address=0x352B9,
        mask=0x80,
    ),
    "Pretty Map G2": BomberTLocationData(
        region="PttyBase",
        type="map",
        code=0x1C2B93,
        address=0x352B9,
        mask=0x8,
    ),

    #Plasma Base
    "Plasma Map 1A2": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BD2,
        address=0x352BD,
        mask=0x4,
    ),
    "Plasma Map 1A1": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BC4,
        address=0x352BC,
        mask=0x10,
    ),
    "Plasma Map 1B1": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BC5,
        address=0x352BC,
        mask=0x20,
    ),
    "Plasma Map 1C1": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BC7,
        address=0x352BC,
        mask=0x80,
    ),
    "Plasma Map 1D1": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BC6,
        address=0x352BC,
        mask=0x40,
    ),
    "Plasma Map 1D0": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BC1,
        address=0x352BC,
        mask=0x2,
    ),
    "Plasma Map 1D2": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BD3,
        address=0x352BD,
        mask=0x8,
    ),
    "Plasma Map 1E2": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BD4,
        address=0x352BD,
        mask=0x10,
    ),
    "Plasma Map 1F2": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BD5,
        address=0x352BD,
        mask=0x20,
    ),
    "Plasma Map 1F1": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BD1,
        address=0x352BD,
        mask=0x2,
    ),
    "Plasma Map 1F0": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BC3,
        address=0x352BC,
        mask=0x8,
    ),
    "Plasma Map 1E0": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BC2,
        address=0x352BC,
        mask=0x4,
    ),
    "Plasma Map 1E1": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BD0,
        address=0x352BD,
        mask=0x1,
    ),
    "Plasma Map 2F1": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BE6,
        address=0x352BE,
        mask=0x40,
    ),
    "Plasma Map 2E1": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BE5,
        address=0x352BE,
        mask=0x20,
    ),
    "Plasma Map 2D1": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BE3,
        address=0x352BE,
        mask=0x8,
    ),
    "Plasma Map 2C1": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BE4,
        address=0x352BE,
        mask=0x10,
    ),
    "Plasma Map 2C2": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BF1,
        address=0x352BF,
        mask=0x2,
    ),
    "Plasma Map 2C0": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BE0,
        address=0x352BE,
        mask=0x1,
    ),
    "Plasma Map 2B0": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BD7,
        address=0x352BD,
        mask=0x80,
    ),
    "Plasma Map 2A0": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BD6,
        address=0x352BD,
        mask=0x40,
    ),
    "Plasma Map 2A1": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BE1,
        address=0x352BE,
        mask=0x2,
    ),
    "Plasma Map 2A2": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BE7,
        address=0x352BE,
        mask=0x80,
    ),
    "Plasma Map 2B2": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BF0,
        address=0x352BF,
        mask=0x1,
    ),
    "Plasma Map 2B1": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BE2,
        address=0x352BE,
        mask=0x4,
    ),
    "Plasma Map 3A1": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BF5,
        address=0x352BF,
        mask=0x20,
    ),
    "Plasma Map 3B1": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BF6,
        address=0x352BF,
        mask=0x40,
    ),
    "Plasma Map 3C1": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2C00,
        address=0x352C0,
        mask=0x1,
    ),
    "Plasma Map 3D1": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BF7,
        address=0x352BF,
        mask=0x80,
    ),
    "Plasma Map 3D0": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BF2,
        address=0x352BF,
        mask=0x4,
    ),
    "Plasma Map 3E0": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BF3,
        address=0x352BF,
        mask=0x8,
    ),
    "Plasma Map 3E1": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2C01,
        address=0x352C0,
        mask=0x2,
    ),
    "Plasma Map 3D2": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2C03,
        address=0x352C0,
        mask=0x8,
    ),
    "Plasma Map 3E2": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2C04,
        address=0x352C0,
        mask=0x10,
    ),
    "Plasma Map 3F2": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2C05,
        address=0x352C0,
        mask=0x20,
    ),
    "Plasma Map 3F1": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2C02,
        address=0x352C0,
        mask=0x4,
    ),
    "Plasma Map 3F0": BomberTLocationData(
        region="PlzmBase",
        type="map",
        code=0x1C2BF4,
        address=0x352BF,
        mask=0x10,
    ),
    # Golem Base
    "Golem Map 1B4": BomberTLocationData(
        region="GlmBase",
        type="map",
        code=0x1C2C33,
        address=0x352C3,
        mask=0x8,
    ),
}

map_location_table = {name: data.code for name, data in loc_map_data_table.items() if data.code is not None}
#locked_locations = {name: data for name, data in loc_map_data_table.items() if data.locked_item}